export const PROPERTY_FETCH_REQUEST = 'PROPERTY_FETCH_REQUEST'
export const PROPERTY_FETCH_SUCCESS = 'PROPERTY_FETCH_SUCCESS'
export const PROPERTY_FETCH_FAIL = 'PROPERTY_FETCH_FAIL'

export const PROPERTY_LIST_UPDATE = 'PROPERTY_LIST_UPDATE' 

export const PROPERTY_BLOCK_REQUEST = 'PROPERTY_BLOCK_REQUEST' 
export const PROPERTY_BLOCK_SUCCESS = 'PROPERTY_BLOCK_SUCCESS'
export const PROPERTY_BLOCK_FAIL = 'PROPERTY_BLOCK_FAIL'

export const ADD_PROPERTY_REQUEST = 'ADD_PROPERTY_REQUEST'
export const ADD_PROPERTY_SUCCESS = 'ADD_PROPERTY_SUCCESS'
export const ADD_PROPERTY_FAIL = 'ADD_PROPERTY_FAIL'