export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_LIST_FETCH_REQUEST = 'USER_LIST_FETCH_REQUEST'
export const USER_LIST_FETCH_SUCCESS = 'USER_LIST_FETCH_SUCCESS'
export const USER_LIST_FETCH_FAIL = 'USER_LIST_FETCH_FAIL'


export const USER_BLOCK_REQUEST = 'USER_BLOCK_REQUEST' 
export const USER_BLOCK_SUCCESS = 'USER_BLOCK_SUCCESS'
export const USER_BLOCK_FAIL = 'USER_BLOCK_FAIL'