# Generated by Django 4.2.15 on 2024-08-31 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bed_room', models.PositiveIntegerField()),
                ('bath_room', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('sq_feet', models.PositiveIntegerField()),
                ('listed_on', models.DateTimeField(auto_now_add=True)),
                ('property_type', models.CharField(choices=[('buy', 'Buy'), ('lease', 'Lease'), ('rent', 'Rent')], max_length=10)),
                ('status', models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('rented', 'Rented'), ('leased', 'Leased')], default='available', max_length=10)),
            ],
        ),
    ]
