# Generated by Django 4.2.15 on 2024-09-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_alter_property_options_transaction_rentlease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentlease',
            name='next_payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
