# Generated by Django 4.2.15 on 2024-09-06 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_property_held_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_date', models.DateTimeField(auto_now_add=True)),
                ('maintenance_type', models.CharField(choices=[('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('roofing', 'Roofing'), ('painting', 'Painting'), ('general_repairs', 'General Repairs')], max_length=50)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=50)),
                ('resolved_date', models.DateTimeField(blank=True, null=True)),
                ('propty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property')),
            ],
        ),
    ]
