# Generated by Django 4.2.15 on 2024-09-07 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_maintenance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('qty', models.PositiveIntegerField()),
                ('propty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='property.property')),
            ],
        ),
    ]
